FORMAT: 1A

# Calci

Does Arithmetic calculations.


## Performs Addition [/calci/add/{first_operand}/{second_operand}]

+ Parametrs

    + first_operand (number) - Integer
    + second_operand (number) - Integer

### Addition [GET]

+ Response 200 (application/json)
    
    + Body
            
            {
                "Response":8
            }

## Performs Substraction [/sub{?first_operand,second_operand}]

+ Parametrs

    + first_operand (number) - Integer
    + second_operand (number) - Integer

### Substraction [GET]

+ Response 200 (application/json)
    
    + Body
    
            {
                "Response":4
            }

## Performs Multiplication [/mul]

### Multiplication [POST]

+ Request (application/json)

     + Body
            
            {
                "Request":
                    {
                        "first_operand":0,
                        "second_operand":9
                    }
            }
            
+ Response 201 (application/json)

    + Body
    
            {
                "Response":3
            }