<wsdl:definitions name="MySoaCICD_Demo_BPELProcess" targetNamespace="http://xmlns.oracle.com/MySoaCICD_Demo_App/MySoaCICD_Demo_Prj/MySoaCICD_Demo_BPELProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/MySoaCICD_Demo_App/MySoaCICD_Demo_Prj/MySoaCICD_Demo_BPELProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://MANU:7005/soa-infra/services/default/MySoaCICD_Demo_Prj!1.0-SNAPSHOT/WSDLs/MySoaCICD_Demo_BPELProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="MySoaCICD_Demo_BPELProcess">
        <plnk:role name="MySoaCICD_Demo_BPELProcessProvider" portType="client:MySoaCICD_Demo_BPELProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/MySoaCICD_Demo_App/MySoaCICD_Demo_Prj/MySoaCICD_Demo_BPELProcess" schemaLocation="XMLSchema_-1539479661.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MySoaCICD_Demo_BPELProcessRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="MySoaCICD_Demo_BPELProcessResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="MySoaCICD_Demo_BPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:MySoaCICD_Demo_BPELProcessRequestMessage"/>
            <wsdl:output message="client:MySoaCICD_Demo_BPELProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="MySoaCICD_Demo_BPELProcessSOAP11Binding" type="client:MySoaCICD_Demo_BPELProcess">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="http://xmlns.oracle.com/MySoaCICD_Demo_App/MySoaCICD_Demo_Prj/MySoaCICD_Demo_BPELProcess/process"/>
            <wsdl:input>
                <soap:body use="literal" parts="payload"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="payload"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="mysoacicd_demo_bpelprocess_client_ep">
        <wsdl:port name="MySoaCICD_Demo_BPELProcess_pt" binding="client:MySoaCICD_Demo_BPELProcessSOAP11Binding">
            <soap:address location="http://MANU:7005/soa-infra/services/default/MySoaCICD_Demo_Prj!1.0-SNAPSHOT*soa_502b5441-95f8-4543-a4f5-bb435b615b20/mysoacicd_demo_bpelprocess_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>